[package]
name = "football-game"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diysh = "1.1.1"
serde = "1.0.177"
serde_derive = "1.0.177"
serde_yaml = "0.9.25"
